/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from 'bn.js'
import { Contract, ContractOptions, ContractEventOptions } from 'web3-eth-contract'
import { EventLog } from 'web3-core'
import { EventEmitter } from 'events'
import { Abi, AbiParameter } from 'web3-types' // Using web3-types for v4.16.0
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
} from './types'

// Event types
export type Approval = ContractEventLog<{
  owner: string
  approved: string
  tokenId: string
  0: string
  1: string
  2: string
}>
export type ApprovalForAll = ContractEventLog<{
  owner: string
  operator: string
  approved: boolean
  0: string
  1: string
  2: boolean
}>
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string
  newOwner: string
  0: string
  1: string
}>
export type Transfer = ContractEventLog<{
  from: string
  to: string
  tokenId: string
  0: string
  1: string
  2: string
}>

// Define a custom subscription type to fully mimic ContractLogsSubscription, extending EventEmitter
interface EventSubscription extends EventEmitter {
  options: ContractEventOptions
  callback?: Callback<any>
  abi: Abi[] // Using Abi from web3-types for v4.16.0
  jsonInterface: Abi[] // Using Abi from web3-types for v4.16.0
  _buildSubscriptionParams(options: ContractEventOptions): any[] // Required by ContractLogsSubscription
  formatSubscriptionResult(result: any): any // Required by ContractLogsSubscription
  args: any // Required by ContractLogsSubscription
  _subscriptionManager: any // Required by ContractLogsSubscription
  _returnFormat: any // Required by ContractLogsSubscription
  id: string | number // Required by ContractLogsSubscription
  address: string // Required by ContractLogsSubscription
  lastBlock: any // Required by ContractLogsSubscription
  processSubscriptionData(data: any): any // Required by ContractLogsSubscription
  sendSubscriptionRequest(): any // Required by ContractLogsSubscription
  returnFormat: any // Required by ContractLogsSubscription
  subscribe(callback?: Callback<any>): EventEmitter // Required by ContractLogsSubscription
  subscriptionManager: any // Required by ContractLogsSubscription
  resubscribe(): any // Required by ContractLogsSubscription
  unsubscribe(): any // Required by ContractLogsSubscription
  sendUnsubscribeRequest(): any // Required by ContractLogsSubscription
  _processSubscriptionResult(result: any): any // Required by ContractLogsSubscription
  _processSubscriptionError(error: any): any // Required by ContractLogsSubscription
  _emitter: EventEmitter // Required by ContractLogsSubscription
  setMaxListenerWarningThreshold(max: number): this // Required by ContractLogsSubscription
}

// Define events interface compatible with ContractEventsInterface
interface Soundchain721Events {
  Approval: (options?: ContractEventOptions) => EventSubscription // Returns EventSubscription
  ApprovalForAll: (options?: ContractEventOptions) => EventSubscription // Returns EventSubscription
  OwnershipTransferred: (options?: ContractEventOptions) => EventSubscription // Returns EventSubscription
  Transfer: (options?: ContractEventOptions) => EventSubscription // Returns EventSubscription
  allEvents: (options?: ContractEventOptions) => EventSubscription // Returns EventSubscription
  [eventName: string]: (options?: ContractEventOptions) => EventSubscription // Index signature matches
}

export interface Soundchain721 extends Omit<Contract<any>, 'clone' | 'once'> { // Retained Contract<any> extension
  constructor(jsonInterface: any[], address?: string, options?: ContractOptions): Soundchain721
  clone(): Soundchain721 // Redefined as required
  methods: {
    approve(to: string, tokenId: number | string | BN): NonPayableTransactionObject<void>

    balanceOf(owner: string): NonPayableTransactionObject<string>

    burn(tokenId: number | string | BN): NonPayableTransactionObject<void>

    getApproved(tokenId: number | string | BN): NonPayableTransactionObject<string>

    isApprovedForAll(owner: string, operator: string): NonPayableTransactionObject<boolean>

    name(): NonPayableTransactionObject<string>

    owner(): NonPayableTransactionObject<string>

    ownerOf(tokenId: number | string | BN): NonPayableTransactionObject<string>

    renounceOwnership(): NonPayableTransactionObject<void>

    royaltyInfo(
      tokenId: number | string | BN,
      _salePrice: number | string | BN,
    ): NonPayableTransactionObject<{
      receiver: string
      royaltyAmount: string
      0: string
      1: string
    }>

    royaltyPercentage(arg0: number | string | BN): NonPayableTransactionObject<string>

    royaltyReceivers(arg0: number | string | BN): NonPayableTransactionObject<string>

    safeMint(to: string, _tokenURI: string, _royaltyPercentage: number | string | BN): NonPayableTransactionObject<void>

    'safeTransferFrom(address,address,uint256)'(
      from: string,
      to: string,
      tokenId: number | string | BN,
    ): NonPayableTransactionObject<void>

    'safeTransferFrom(address,address,uint256,bytes)'(
      from: string,
      to: string,
      tokenId: number | string | BN,
      _data: string | number[],
    ): NonPayableTransactionObject<void>

    setApprovalForAll(operator: string, approved: boolean): NonPayableTransactionObject<void>

    setRoyalty(
      tokenId: number | string | BN,
      creator: string,
      _royaltyPercentage: number | string | BN,
    ): NonPayableTransactionObject<void>

    supportsInterface(interfaceId: string | number[]): NonPayableTransactionObject<boolean>

    symbol(): NonPayableTransactionObject<string>

    tokenByIndex(index: number | string | BN): NonPayableTransactionObject<string>

    tokenOfOwnerByIndex(owner: string, index: number | string | BN): NonPayableTransactionObject<string>

    tokenURI(tokenId: number | string | BN): NonPayableTransactionObject<string>

    totalSupply(): NonPayableTransactionObject<string>

    transferFrom(from: string, to: string, tokenId: number | string | BN): NonPayableTransactionObject<void>

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>
  }
  events: Soundchain721Events // Aligned with Contract<any> events
}

export interface Soundchain721Factory extends Omit<Contract<any>, 'clone' | 'once'> { // Retained consistency
  methods: {
    createSoundchain721(
      _name: string,
      _symbol: string,
      _royaltyReceivers: string[],
      _royaltyPercentages: (number | string | BN)[],
    ): NonPayableTransactionObject<Soundchain721>
  }
}
