export enum ModalActionTypes {
  SHOW_NEW_POST = 'SHOW_NEW_POST',
  SET_REPOST_ID = 'SET_REPOST_ID',
  SET_EDIT_POST_ID = 'SET_EDIT_POST_ID',
  SHOW_CONTEXT_MENU = 'SHOW_CONTEXT_MENU',
  SHOW_UNDER_DEVELOPMENT = 'SHOW_UNDER_DEVELOPMENT',
  SHOW_REACTIONS = 'SHOW_REACTIONS',
  HIDE_REACTIONS = 'HIDE_REACTIONS',
  SHOW_NEW_TRACK = 'SHOW_NEW_TRACK',
}
