export enum ModalActionTypes {
  SHOW_NEW_POST = 'SHOW_NEW_POST',
  SET_REPOST_ID = 'SET_REPOST_ID',
  SHOW_DELETE = 'SHOW_DELETE',
  SHOW_UNDER_DEVELOPMENT = 'SHOW_UNDER_DEVELOPMENT',
  SHOW_REACTIONS = 'SHOW_REACTIONS',
  HIDE_REACTIONS = 'HIDE_REACTIONS',
}
