export enum ModalActionTypes {
  SHOW_NEW_POST = 'SHOW_NEW_POST',
  SET_REPOST_ID = 'SET_REPOST_ID',
  SET_EDIT_POST_ID = 'SET_EDIT_POST_ID',
  SHOW_CONTEXT_MENU = 'SHOW_CONTEXT_MENU',
  SHOW_UNDER_DEVELOPMENT = 'SHOW_UNDER_DEVELOPMENT',
  SHOW_REACTIONS = 'SHOW_REACTIONS',
  HIDE_REACTIONS = 'HIDE_REACTIONS',
  SHOW_CREATE = 'SHOW_CREATE',
  SHOW_APPROVE = 'SHOW_APPROVE',
  SHOW_AUDIO_PLAYER = 'SHOW_AUDIO_PLAYER',
  SHOW_TRANSFER_CONFIRMATION = 'SHOW_TRANSFER_CONFIRMATION'
}
