export enum PanelActionTypes {
  OPEN_PANEL = 'OPEN_PANEL',
  CLOSE_PANEL = 'CLOSE_PANEL',
  MINIMIZE_PANEL = 'MINIMIZE_PANEL',
  MAXIMIZE_PANEL = 'MAXIMIZE_PANEL',
  TOGGLE_PANEL = 'TOGGLE_PANEL',
  SET_PANEL_POSITION = 'SET_PANEL_POSITION',
  SET_PANEL_SCROLL = 'SET_PANEL_SCROLL',
  BRING_TO_FRONT = 'BRING_TO_FRONT',
  CLOSE_ALL_PANELS = 'CLOSE_ALL_PANELS',
}
