declare module 'vanta/dist/vanta.birds.min'
declare module 'vanta/dist/vanta.cells.min'
declare module 'vanta/dist/vanta.fog.min'
declare module 'vanta/dist/vanta.net.min'
declare module 'vanta/dist/vanta.rings.min'
declare module 'vanta/dist/vanta.waves.min'
