#!/usr/bin/env node
/**
 * Build-time emote prefetch.
 *
 * Hits the four public emote catalogs ONCE during `next build`, writes the
 * dedup'd, validated list to src/lib/emotes.generated.ts. The runtime then
 * imports it as a static array — no network round-trip on modal open.
 *
 * Catalogs:
 *   - 7TV global set (cdn.7tv.app)
 *   - BetterTTV global (cdn.betterttv.net)
 *   - FrankerFaceZ global (cdn.frankerfacez.com)
 *
 * Failures are non-fatal — if a source 503s during build, the build still
 * succeeds with an empty array for that source. Catalog refreshes happen on
 * every Vercel rebuild, which is plenty fresh for surfaces that rarely
 * change (BTTV/FFZ globals update maybe quarterly).
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const SEVEN_TV_CDN = 'https://cdn.7tv.app/emote'
const BTTV_CDN = 'https://cdn.betterttv.net/emote'

async function fetch7tvGlobal() {
  try {
    const r = await fetch('https://7tv.io/v3/emote-sets/global')
    if (!r.ok) {
      console.warn(`[emotes] 7TV global ${r.status}`)
      return []
    }
    const j = await r.json()
    const items = j?.emotes || []
    return items.map((e) => ({
      id: `s7g-${e.id}`,
      name: e.name,
      url: `${SEVEN_TV_CDN}/${e.id}/2x`,
    }))
  } catch (err) {
    console.warn('[emotes] 7TV global failed:', err.message)
    return []
  }
}

async function fetchBttvGlobal() {
  try {
    const r = await fetch('https://api.betterttv.net/3/cached/emotes/global')
    if (!r.ok) {
      console.warn(`[emotes] BTTV global ${r.status}`)
      return []
    }
    const items = await r.json()
    return items.map((e) => ({
      id: `btv-${e.id}`,
      name: e.code,
      url: `${BTTV_CDN}/${e.id}/2x.${e.imageType || 'webp'}`,
    }))
  } catch (err) {
    console.warn('[emotes] BTTV global failed:', err.message)
    return []
  }
}

async function fetchFfzGlobal() {
  try {
    const r = await fetch('https://api.frankerfacez.com/v1/set/global')
    if (!r.ok) {
      console.warn(`[emotes] FFZ global ${r.status}`)
      return []
    }
    const j = await r.json()
    const out = []
    const sets = j?.sets || {}
    for (const setKey of Object.keys(sets)) {
      const emotes = sets[setKey]?.emoticons || []
      for (const e of emotes) {
        const urls = e?.urls || {}
        const url = urls['2'] || urls['1'] || urls['4']
        if (!url) continue
        const full = url.startsWith('//') ? `https:${url}` : url
        out.push({ id: `ffz-${e.id}`, name: e.name, url: full })
      }
    }
    return out
  } catch (err) {
    console.warn('[emotes] FFZ global failed:', err.message)
    return []
  }
}

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const OUTPUT = join(__dirname, '..', 'src', 'lib', 'emotes.generated.ts')

const start = Date.now()
const [seven, bttv, ffz] = await Promise.all([
  fetch7tvGlobal(),
  fetchBttvGlobal(),
  fetchFfzGlobal(),
])

// Dedup by URL across all sources (some emotes appear in multiple catalogs).
const seen = new Set()
const all = []
for (const list of [seven, bttv, ffz]) {
  for (const e of list) {
    if (seen.has(e.url)) continue
    seen.add(e.url)
    all.push(e)
  }
}

const ms = Date.now() - start
const ts = new Date().toISOString()

const content = `// AUTO-GENERATED by scripts/fetch-emotes.mjs at ${ts}
// Do not edit by hand. Re-run \`yarn build\` (or \`node scripts/fetch-emotes.mjs\`) to refresh.
// Sources: 7TV global, BetterTTV global, FrankerFaceZ global. Total ${all.length} emotes.

import type { ArenaEmote } from './emotes'

export const PREFETCHED_EMOTES: ArenaEmote[] = ${JSON.stringify(all, null, 2)}
`

writeFileSync(OUTPUT, content, 'utf8')
console.log(
  `[emotes] Prefetched ${all.length} (7TV ${seven.length} + BTTV ${bttv.length} + FFZ ${ffz.length}, dedup'd) in ${ms}ms → src/lib/emotes.generated.ts`,
)
