import * as Sentry from '@sentry/node';
import { ListingCountByTrackEdition } from '../loaders/ListingCountByTrackEdition';
import { User } from '../models/User';
import { AuctionItemService } from '../services/AuctionItemService';
import { AudioHolderService } from '../services/AudioHolderService';
import { AuthService } from '../services/AuthService';
import { BidService } from '../services/BidService';
import { BlockTrackerService } from '../services/BlockTrackerService';
import { BuyNowService } from '../services/BuyNowItemService';
import { CommentService } from '../services/CommentService';
import { EmailService } from '../services/EmailService';
import { EmbedService } from '../services/EmbedService';
import { ExploreService } from '../services/ExploreService';
import { FeedService } from '../services/FeedService';
import { FollowService } from '../services/FollowService';
import { JwtService, JwtUser } from '../services/JwtService';
import { ListingItemService } from '../services/ListingItemService';
import { LogErrorService } from '../services/LogErrorService';
import { MailchimpService } from '../services/MailchimpService';
import { MessageService } from '../services/MessageService';
import { MuxService } from '../services/MuxService';
import { NotificationService } from '../services/NotificationService';
import { PinningService } from '../services/PinningService';
import { PolygonscanService } from '../services/PolygonService';
import { PostService } from '../services/PostService';
import { ProfileService } from '../services/ProfileService';
import { ProfileVerificationRequestService } from '../services/ProfileVerificationRequestService';
import { ProofBookService } from '../services/ProofBookService';
import { ReactionService } from '../services/ReactionService';
import { SubscriptionService } from '../services/SubscriptionService';
import { TrackEditionService } from '../services/TrackEditionService';
import { TrackService } from '../services/TrackService';
import { UploadService } from '../services/UploadService';
import { UserService } from '../services/UserService';
import { WhitelistEntryService } from '../services/WhitelistEntryService';
import { PlaylistService } from '../services/PlaylistService';

export class Context {
  auctionItemService: AuctionItemService;
  authService: AuthService;
  blockTrackerService: BlockTrackerService;
  buyNowItemService: BuyNowService;
  commentService: CommentService;
  emailService: EmailService;
  embedService: EmbedService;
  exploreService: ExploreService;
  feedService: FeedService;
  followService: FollowService;
  jwtService: JwtService;
  logErrorService: LogErrorService;
  messageService: MessageService;
  muxService: MuxService;
  notificationService: NotificationService;
  pinningService: PinningService;
  polygonscanService: PolygonscanService;
  postService: PostService;
  playlistService: PlaylistService;
  profileService: ProfileService;
  proofBookService: ProofBookService;
  profileVerificationRequestService: ProfileVerificationRequestService;
  reactionService: ReactionService;
  subscriptionService: SubscriptionService;
  trackService: TrackService;
  uploadService: UploadService;
  userService: UserService;
  bidService: BidService;
  listingItemService: ListingItemService;
  user?: Promise<User>;
  whitelistEntryService: WhitelistEntryService;
  audioHolderService: AudioHolderService;
  trackEditionService: TrackEditionService;
  listingCountByTrackEdition = ListingCountByTrackEdition();
  sentryTransaction = Sentry.startTransaction({
    op: 'gql',
    name: 'GraphQLTransaction',
  });
  mailchimpService: MailchimpService;

  constructor(jwtUser?: JwtUser) {
    this.auctionItemService = new AuctionItemService(this);
    this.authService = new AuthService(this);
    this.blockTrackerService = new BlockTrackerService(this);
    this.buyNowItemService = new BuyNowService(this);
    this.commentService = new CommentService(this);
    this.emailService = new EmailService(this);
    this.embedService = new EmbedService(this);
    this.exploreService = new ExploreService(this);
    this.feedService = new FeedService(this);
    this.followService = new FollowService(this);
    this.jwtService = new JwtService(this);
    this.logErrorService = new LogErrorService(this);
    this.messageService = new MessageService(this);
    this.muxService = new MuxService(this);
    this.notificationService = new NotificationService(this);
    this.pinningService = new PinningService(this);
    this.polygonscanService = new PolygonscanService(this);
    this.postService = new PostService(this);
    this.playlistService = new PlaylistService(this);
    this.profileService = new ProfileService(this);
    this.proofBookService = new ProofBookService(this);
    this.profileVerificationRequestService = new ProfileVerificationRequestService(this);
    this.reactionService = new ReactionService(this);
    this.subscriptionService = new SubscriptionService(this);
    this.trackService = new TrackService(this);
    this.uploadService = new UploadService(this);
    this.userService = new UserService(this);
    this.bidService = new BidService(this);
    this.listingItemService = new ListingItemService(this);
    this.whitelistEntryService = new WhitelistEntryService(this);
    this.audioHolderService = new AudioHolderService(this);
    this.trackEditionService = new TrackEditionService(this);
    this.mailchimpService = new MailchimpService(this);
    this.user = jwtUser && this.userService.getUser(jwtUser.sub);
  }
}
