// AUTO-GENERATED by scripts/fetch-emotes.mjs at 2026-06-03T20:03:52.419Z
// Do not edit by hand. Re-run `yarn prefetch:emotes` (or any build) to refresh.
// Total 132 emotes (7TV 44 + BTTV 65 + FFZ 23).

export interface PrefetchedEmote {
  id: string
  name: string
  url: string
  animated: boolean
  source: '7tv' | 'bttv' | 'ffz' | 'twitch' | 'kick' | 'tenor' | 'soundchain'
}

export const PREFETCHED_STICKER_EMOTES: Record<'7tv' | 'bttv' | 'ffz', PrefetchedEmote[]> = {
  '7tv': [
  {
    "id": "01FCY771D800007PQ2DF3GDTN6",
    "name": "RainTime",
    "url": "https://cdn.7tv.app/emote/01FCY771D800007PQ2DF3GDTN6/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01FE3XY508000AA32JP519W2EW",
    "name": "PETPET",
    "url": "https://cdn.7tv.app/emote/01FE3XY508000AA32JP519W2EW/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GGD5PJA8000FH13S498E9D8X",
    "name": "ppL",
    "url": "https://cdn.7tv.app/emote/01GGD5PJA8000FH13S498E9D8X/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB2TN09G000AZXHZ8HNEZX6G",
    "name": "Clap2",
    "url": "https://cdn.7tv.app/emote/01GB2TN09G000AZXHZ8HNEZX6G/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GAM8EFQ00004MXFXAJYKA859",
    "name": "Clap",
    "url": "https://cdn.7tv.app/emote/01GAM8EFQ00004MXFXAJYKA859/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GAFTZ9K80003DHH026MC7JW0",
    "name": "PepePls",
    "url": "https://cdn.7tv.app/emote/01GAFTZ9K80003DHH026MC7JW0/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GAZ199Z8000FEWHS6AT5QZV0",
    "name": "peepoHappy",
    "url": "https://cdn.7tv.app/emote/01GAZ199Z8000FEWHS6AT5QZV0/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GAZ4SBX80007YCE2RXBT44B2",
    "name": "peepoSad",
    "url": "https://cdn.7tv.app/emote/01GAZ4SBX80007YCE2RXBT44B2/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB9W8JN80004CKF2H1TWA99H",
    "name": "FeelsDankMan",
    "url": "https://cdn.7tv.app/emote/01GB9W8JN80004CKF2H1TWA99H/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB2S7H7000018VJGJ4A9BMFS",
    "name": "BillyApprove",
    "url": "https://cdn.7tv.app/emote/01GB2S7H7000018VJGJ4A9BMFS/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GB8EQNJ8000497KFBZWNSDFZ",
    "name": "forsenPls",
    "url": "https://cdn.7tv.app/emote/01GB8EQNJ8000497KFBZWNSDFZ/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GB54CZTG0004ZBZEDT30HE2M",
    "name": "RoxyPotato",
    "url": "https://cdn.7tv.app/emote/01GB54CZTG0004ZBZEDT30HE2M/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB4P2HX0000BJ5HR8F6XV9Q0",
    "name": "gachiBASS",
    "url": "https://cdn.7tv.app/emote/01GB4P2HX0000BJ5HR8F6XV9Q0/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GKQXGX1R000216YB0K7GN92X",
    "name": "(7TV)",
    "url": "https://cdn.7tv.app/emote/01GKQXGX1R000216YB0K7GN92X/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01FKSDK14G0008TM5NY9QEG0QV",
    "name": "PartyParrot",
    "url": "https://cdn.7tv.app/emote/01FKSDK14G0008TM5NY9QEG0QV/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GB5VC57000003DZTMZQNY944",
    "name": "RebeccaBlack",
    "url": "https://cdn.7tv.app/emote/01GB5VC57000003DZTMZQNY944/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01F014S6KG0007E4VV006YKSM3",
    "name": "reckH",
    "url": "https://cdn.7tv.app/emote/01F014S6KG0007E4VV006YKSM3/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01G98W833R0000BRQD106P0ZNT",
    "name": "WAYTOODANK",
    "url": "https://cdn.7tv.app/emote/01G98W833R0000BRQD106P0ZNT/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GB2ZJFBG000DTBJYANG8XYFP",
    "name": "AlienDance",
    "url": "https://cdn.7tv.app/emote/01GB2ZJFBG000DTBJYANG8XYFP/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01G4GQC5H0000D3DGNAYJJP8EB",
    "name": "Gayge",
    "url": "https://cdn.7tv.app/emote/01G4GQC5H0000D3DGNAYJJP8EB/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GGCQPCGR000C7MT8JZGP6E89",
    "name": "ApuApustaja",
    "url": "https://cdn.7tv.app/emote/01GGCQPCGR000C7MT8JZGP6E89/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB9W2CDG000BFSD141G0MGSA",
    "name": "BasedGod",
    "url": "https://cdn.7tv.app/emote/01GB9W2CDG000BFSD141G0MGSA/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01G98V5RFG0001CD052SPS435F",
    "name": "GuitarTime",
    "url": "https://cdn.7tv.app/emote/01G98V5RFG0001CD052SPS435F/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01HM524VE80004SKSHMCZWXH1T",
    "name": "peepoPls",
    "url": "https://cdn.7tv.app/emote/01HM524VE80004SKSHMCZWXH1T/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01HM4P26CR000449DZBT4FVMA5",
    "name": "TeaTime",
    "url": "https://cdn.7tv.app/emote/01HM4P26CR000449DZBT4FVMA5/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01HM4PGHC80007635TAZG67FT5",
    "name": "WineTime",
    "url": "https://cdn.7tv.app/emote/01HM4PGHC80007635TAZG67FT5/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01G98V81Q80000BRQD106P0ZEK",
    "name": "PianoTime",
    "url": "https://cdn.7tv.app/emote/01G98V81Q80000BRQD106P0ZEK/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01G98TT6BR000A39K5ZSQFTPWR",
    "name": "CrayonTime",
    "url": "https://cdn.7tv.app/emote/01G98TT6BR000A39K5ZSQFTPWR/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01HM6NJ2X000035ZKVAPWBNW26",
    "name": "nymnCorn",
    "url": "https://cdn.7tv.app/emote/01HM6NJ2X000035ZKVAPWBNW26/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01HM2F7Q1R00022X3E2804NBNQ",
    "name": "SteerR",
    "url": "https://cdn.7tv.app/emote/01HM2F7Q1R00022X3E2804NBNQ/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01J107C3E8000DX4MZBQSYGRXS",
    "name": "sevenTV",
    "url": "https://cdn.7tv.app/emote/01J107C3E8000DX4MZBQSYGRXS/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01FTEZEE900001E12995B12GR4",
    "name": "nanaAYAYA",
    "url": "https://cdn.7tv.app/emote/01FTEZEE900001E12995B12GR4/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01J8NMZ2HG0005G1FWF2H9Y615",
    "name": "BibleThump",
    "url": "https://cdn.7tv.app/emote/01J8NMZ2HG0005G1FWF2H9Y615/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01H16FA16G0005EZED5J0EY7KN",
    "name": "glorp",
    "url": "https://cdn.7tv.app/emote/01H16FA16G0005EZED5J0EY7KN/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GG3YGWK8000DWE419062SG28",
    "name": "Stare",
    "url": "https://cdn.7tv.app/emote/01GG3YGWK8000DWE419062SG28/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01JY2MX5BE5BVWWFV153ANMMHZ",
    "name": "aceStare",
    "url": "https://cdn.7tv.app/emote/01JY2MX5BE5BVWWFV153ANMMHZ/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01F9EM2ETG000E7SC8F953GXCX",
    "name": "gachiGASM",
    "url": "https://cdn.7tv.app/emote/01F9EM2ETG000E7SC8F953GXCX/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB32XE6R00018VJGJ4A9BNCV",
    "name": "AYAYA",
    "url": "https://cdn.7tv.app/emote/01GB32XE6R00018VJGJ4A9BNCV/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB4XE3ZR000DKFRGM9Q1M7VS",
    "name": "RareParrot",
    "url": "https://cdn.7tv.app/emote/01GB4XE3ZR000DKFRGM9Q1M7VS/2x.webp",
    "animated": true,
    "source": "7tv"
  },
  {
    "id": "01GB4FWTR8000DGEZ8VYY59RBN",
    "name": "FeelsWeirdMan",
    "url": "https://cdn.7tv.app/emote/01GB4FWTR8000DGEZ8VYY59RBN/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB4CK01800090V9B3D8CGEEX",
    "name": "EZ",
    "url": "https://cdn.7tv.app/emote/01GB4CK01800090V9B3D8CGEEX/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB46137R000BJ5HR8F6XV8J1",
    "name": "FeelsOkayMan",
    "url": "https://cdn.7tv.app/emote/01GB46137R000BJ5HR8F6XV8J1/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GB4EV0Q800090V9B3D8CGEHV",
    "name": "FeelsStrongMan",
    "url": "https://cdn.7tv.app/emote/01GB4EV0Q800090V9B3D8CGEHV/2x.webp",
    "animated": false,
    "source": "7tv"
  },
  {
    "id": "01GBFDVP18000CRDCG0DV7KEMY",
    "name": "7Cinema",
    "url": "https://cdn.7tv.app/emote/01GBFDVP18000CRDCG0DV7KEMY/2x.webp",
    "animated": false,
    "source": "7tv"
  }
],
  'bttv': [
  {
    "id": "54fa8f1401e468494b85b537",
    "name": ":tf:",
    "url": "https://cdn.betterttv.net/emote/54fa8f1401e468494b85b537/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa8fce01e468494b85b53c",
    "name": "CiGrip",
    "url": "https://cdn.betterttv.net/emote/54fa8fce01e468494b85b53c/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa903b01e468494b85b53f",
    "name": "DatSauce",
    "url": "https://cdn.betterttv.net/emote/54fa903b01e468494b85b53f/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa909b01e468494b85b542",
    "name": "ForeverAlone",
    "url": "https://cdn.betterttv.net/emote/54fa909b01e468494b85b542/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa90ba01e468494b85b543",
    "name": "GabeN",
    "url": "https://cdn.betterttv.net/emote/54fa90ba01e468494b85b543/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa90f201e468494b85b545",
    "name": "HailHelix",
    "url": "https://cdn.betterttv.net/emote/54fa90f201e468494b85b545/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa932201e468494b85b555",
    "name": "ShoopDaWhoop",
    "url": "https://cdn.betterttv.net/emote/54fa932201e468494b85b555/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fab45f633595ca4c713abc",
    "name": "M&Mjc",
    "url": "https://cdn.betterttv.net/emote/54fab45f633595ca4c713abc/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fab7d2633595ca4c713abf",
    "name": "bttvNice",
    "url": "https://cdn.betterttv.net/emote/54fab7d2633595ca4c713abf/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa935601e468494b85b557",
    "name": "TwaT",
    "url": "https://cdn.betterttv.net/emote/54fa935601e468494b85b557/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fa99b601e468494b85b55d",
    "name": "WatChuSay",
    "url": "https://cdn.betterttv.net/emote/54fa99b601e468494b85b55d/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca11a65dbbdab32ec0558",
    "name": "tehPoleCat",
    "url": "https://cdn.betterttv.net/emote/566ca11a65dbbdab32ec0558/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca1a365dbbdab32ec055b",
    "name": "AngelThump",
    "url": "https://cdn.betterttv.net/emote/566ca1a365dbbdab32ec055b/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fbefeb01abde735115de5b",
    "name": "TaxiBro",
    "url": "https://cdn.betterttv.net/emote/54fbefeb01abde735115de5b/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fbf00a01abde735115de5c",
    "name": "BroBalt",
    "url": "https://cdn.betterttv.net/emote/54fbf00a01abde735115de5c/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "54fbf09c01abde735115de61",
    "name": "CandianRage",
    "url": "https://cdn.betterttv.net/emote/54fbf09c01abde735115de61/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "55028cd2135896936880fdd7",
    "name": "D:",
    "url": "https://cdn.betterttv.net/emote/55028cd2135896936880fdd7/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "550352766f86a5b26c281ba2",
    "name": "VisLaud",
    "url": "https://cdn.betterttv.net/emote/550352766f86a5b26c281ba2/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "550b344bff8ecee922d2a3c1",
    "name": "KaRappa",
    "url": "https://cdn.betterttv.net/emote/550b344bff8ecee922d2a3c1/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca00f65dbbdab32ec0544",
    "name": "FishMoley",
    "url": "https://cdn.betterttv.net/emote/566ca00f65dbbdab32ec0544/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca02865dbbdab32ec0547",
    "name": "Hhhehehe",
    "url": "https://cdn.betterttv.net/emote/566ca02865dbbdab32ec0547/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca04265dbbdab32ec054a",
    "name": "KKona",
    "url": "https://cdn.betterttv.net/emote/566ca04265dbbdab32ec054a/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca09365dbbdab32ec0555",
    "name": "PoleDoge",
    "url": "https://cdn.betterttv.net/emote/566ca09365dbbdab32ec0555/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "553b48a21f145f087fc15ca6",
    "name": "sosGame",
    "url": "https://cdn.betterttv.net/emote/553b48a21f145f087fc15ca6/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "55471c2789d53f2d12781713",
    "name": "CruW",
    "url": "https://cdn.betterttv.net/emote/55471c2789d53f2d12781713/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "555015b77676617e17dd2e8e",
    "name": "RarePepe",
    "url": "https://cdn.betterttv.net/emote/555015b77676617e17dd2e8e/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "555981336ba1901877765555",
    "name": "haHAA",
    "url": "https://cdn.betterttv.net/emote/555981336ba1901877765555/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "55b6524154eefd53777b2580",
    "name": "FeelsBirthdayMan",
    "url": "https://cdn.betterttv.net/emote/55b6524154eefd53777b2580/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "55f324c47f08be9f0a63cce0",
    "name": "RonSmug",
    "url": "https://cdn.betterttv.net/emote/55f324c47f08be9f0a63cce0/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "560577560874de34757d2dc0",
    "name": "KappaCool",
    "url": "https://cdn.betterttv.net/emote/560577560874de34757d2dc0/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566c9fc265dbbdab32ec053b",
    "name": "FeelsBadMan",
    "url": "https://cdn.betterttv.net/emote/566c9fc265dbbdab32ec053b/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566c9f3b65dbbdab32ec052e",
    "name": "bUrself",
    "url": "https://cdn.betterttv.net/emote/566c9f3b65dbbdab32ec052e/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566c9f6365dbbdab32ec0532",
    "name": "ConcernDoge",
    "url": "https://cdn.betterttv.net/emote/566c9f6365dbbdab32ec0532/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566c9fde65dbbdab32ec053e",
    "name": "FeelsGoodMan",
    "url": "https://cdn.betterttv.net/emote/566c9fde65dbbdab32ec053e/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566c9ff365dbbdab32ec0541",
    "name": "FireSpeed",
    "url": "https://cdn.betterttv.net/emote/566c9ff365dbbdab32ec0541/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca06065dbbdab32ec054e",
    "name": "NaM",
    "url": "https://cdn.betterttv.net/emote/566ca06065dbbdab32ec054e/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566ca38765dbbdab32ec0560",
    "name": "SourPls",
    "url": "https://cdn.betterttv.net/emote/566ca38765dbbdab32ec0560/2x.gif",
    "animated": true,
    "source": "bttv"
  },
  {
    "id": "566dde0e65dbbdab32ec068f",
    "name": "FeelsSnowMan",
    "url": "https://cdn.betterttv.net/emote/566dde0e65dbbdab32ec068f/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "566decae65dbbdab32ec0699",
    "name": "FeelsSnowyMan",
    "url": "https://cdn.betterttv.net/emote/566decae65dbbdab32ec0699/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "567b00c61ddbe1786688a633",
    "name": "LuL",
    "url": "https://cdn.betterttv.net/emote/567b00c61ddbe1786688a633/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "56901914991f200c34ffa656",
    "name": "SaltyCorn",
    "url": "https://cdn.betterttv.net/emote/56901914991f200c34ffa656/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "56e9f494fff3cc5c35e5287e",
    "name": "monkaS",
    "url": "https://cdn.betterttv.net/emote/56e9f494fff3cc5c35e5287e/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "56f5be00d48006ba34f530a4",
    "name": "VapeNation",
    "url": "https://cdn.betterttv.net/emote/56f5be00d48006ba34f530a4/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "56fa09f18eff3b595e93ac26",
    "name": "ariW",
    "url": "https://cdn.betterttv.net/emote/56fa09f18eff3b595e93ac26/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5709ab688eff3b595e93c595",
    "name": "notsquishY",
    "url": "https://cdn.betterttv.net/emote/5709ab688eff3b595e93c595/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5733ff12e72c3c0814233e20",
    "name": "FeelsAmazingMan",
    "url": "https://cdn.betterttv.net/emote/5733ff12e72c3c0814233e20/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "573d38b50ffbf6cc5cc38dc9",
    "name": "DuckerZ",
    "url": "https://cdn.betterttv.net/emote/573d38b50ffbf6cc5cc38dc9/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "580e438942170bfd57189866",
    "name": "FeelsPumpkinMan",
    "url": "https://cdn.betterttv.net/emote/580e438942170bfd57189866/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "59cf182fcbe2693d59d7bf46",
    "name": "SqShy",
    "url": "https://cdn.betterttv.net/emote/59cf182fcbe2693d59d7bf46/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "58d2e73058d8950a875ad027",
    "name": "Wowee",
    "url": "https://cdn.betterttv.net/emote/58d2e73058d8950a875ad027/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5dc36a8db537d747e37ac187",
    "name": "WubTF",
    "url": "https://cdn.betterttv.net/emote/5dc36a8db537d747e37ac187/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5e76d2ab8c0f5c3723a9a87d",
    "name": "cvR",
    "url": "https://cdn.betterttv.net/emote/5e76d2ab8c0f5c3723a9a87d/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5e76d2d2d112fc372574d222",
    "name": "cvL",
    "url": "https://cdn.betterttv.net/emote/5e76d2d2d112fc372574d222/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5e76d338d6581c3724c0f0b2",
    "name": "cvHazmat",
    "url": "https://cdn.betterttv.net/emote/5e76d338d6581c3724c0f0b2/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5e76d399d6581c3724c0f0b8",
    "name": "cvMask",
    "url": "https://cdn.betterttv.net/emote/5e76d399d6581c3724c0f0b8/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "5ffdf28dc96152314ad63960",
    "name": "DogChamp",
    "url": "https://cdn.betterttv.net/emote/5ffdf28dc96152314ad63960/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "6468f7acaee1f7f47567708e",
    "name": "c!",
    "url": "https://cdn.betterttv.net/emote/6468f7acaee1f7f47567708e/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "6468f845aee1f7f47567709b",
    "name": "h!",
    "url": "https://cdn.betterttv.net/emote/6468f845aee1f7f47567709b/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "6468f869aee1f7f4756770a8",
    "name": "l!",
    "url": "https://cdn.betterttv.net/emote/6468f869aee1f7f4756770a8/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "6468f883aee1f7f4756770b5",
    "name": "r!",
    "url": "https://cdn.betterttv.net/emote/6468f883aee1f7f4756770b5/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "6468f89caee1f7f4756770c2",
    "name": "v!",
    "url": "https://cdn.betterttv.net/emote/6468f89caee1f7f4756770c2/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "6468f8d1aee1f7f4756770cf",
    "name": "z!",
    "url": "https://cdn.betterttv.net/emote/6468f8d1aee1f7f4756770cf/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "64e3b31920cb0d25d950a9f9",
    "name": "w!",
    "url": "https://cdn.betterttv.net/emote/64e3b31920cb0d25d950a9f9/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "65cbe7dbaed093b2eaf87c65",
    "name": "p!",
    "url": "https://cdn.betterttv.net/emote/65cbe7dbaed093b2eaf87c65/2x.png",
    "animated": false,
    "source": "bttv"
  },
  {
    "id": "662953eeea369c0ece39eb93",
    "name": "s!",
    "url": "https://cdn.betterttv.net/emote/662953eeea369c0ece39eb93/2x.png",
    "animated": false,
    "source": "bttv"
  }
],
  'ffz': [
  {
    "id": "9",
    "name": "ZrehplaR",
    "url": "https://cdn.frankerfacez.com/emote/9/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "6",
    "name": "YooHoo",
    "url": "https://cdn.frankerfacez.com/emote/6/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "4",
    "name": "ManChicken",
    "url": "https://cdn.frankerfacez.com/emote/4/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "3",
    "name": "BeanieHipster",
    "url": "https://cdn.frankerfacez.com/emote/3/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "25927",
    "name": "CatBag",
    "url": "https://cdn.frankerfacez.com/emote/25927/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "27081",
    "name": "ZreknarF",
    "url": "https://cdn.frankerfacez.com/emote/27081/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "28136",
    "name": "LilZ",
    "url": "https://cdn.frankerfacez.com/emote/28136/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "28138",
    "name": "ZliL",
    "url": "https://cdn.frankerfacez.com/emote/28138/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "149346",
    "name": "LaterSooner",
    "url": "https://cdn.frankerfacez.com/emote/149346/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "142673",
    "name": "BORT",
    "url": "https://cdn.frankerfacez.com/emote/142673/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "757384",
    "name": "BibleThump",
    "url": "https://cdn.frankerfacez.com/emote/757384/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "720507",
    "name": "ffzHyper",
    "url": "https://cdn.frankerfacez.com/emote/720507/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "720510",
    "name": "ffzRainbow",
    "url": "https://cdn.frankerfacez.com/emote/720510/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "721137",
    "name": "ffzBounce",
    "url": "https://cdn.frankerfacez.com/emote/721137/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "720730",
    "name": "ffzJam",
    "url": "https://cdn.frankerfacez.com/emote/720730/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "723889",
    "name": "ffzSlide",
    "url": "https://cdn.frankerfacez.com/emote/723889/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "723887",
    "name": "ffzLeave",
    "url": "https://cdn.frankerfacez.com/emote/723887/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "723888",
    "name": "ffzArrive",
    "url": "https://cdn.frankerfacez.com/emote/723888/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "723886",
    "name": "ffzSpin",
    "url": "https://cdn.frankerfacez.com/emote/723886/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "723890",
    "name": "ffzW",
    "url": "https://cdn.frankerfacez.com/emote/723890/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "720508",
    "name": "ffzX",
    "url": "https://cdn.frankerfacez.com/emote/720508/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "720509",
    "name": "ffzY",
    "url": "https://cdn.frankerfacez.com/emote/720509/2",
    "animated": false,
    "source": "ffz"
  },
  {
    "id": "720729",
    "name": "ffzCursed",
    "url": "https://cdn.frankerfacez.com/emote/720729/2",
    "animated": false,
    "source": "ffz"
  }
],
}
