#!/usr/bin/env node
/**
 * Build-time emote prefetch for web/'s StickerPicker.
 *
 * Mirrors the runtime fetches in src/components/StickerPicker.tsx so the
 * StickerPicker can render instantly on first open instead of waiting on
 * three sequential API round-trips.
 *
 * Sources prefetched:
 *   - 7TV global set     (cdn.7tv.app)
 *   - BetterTTV global   (cdn.betterttv.net)
 *   - FrankerFaceZ global (cdn.frankerfacez.com)
 *
 * NOT prefetched:
 *   - Twitch globals — already a static array in StickerPicker, no network
 *   - Kick-style sets — referenced 7TV set IDs were stale (404); skipped
 *
 * Output: src/lib/stickerEmotes.generated.ts (gitignored — regenerated each build).
 *
 * Failures are non-fatal — if a source 503s during build, we still write a
 * file with empty arrays for that source. The StickerPicker's existing
 * runtime fetch functions act as a safety net (they live-fetch on cache miss).
 */

import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'

const SEVEN_TV_CDN = 'https://cdn.7tv.app/emote'
const BTTV_CDN = 'https://cdn.betterttv.net/emote'

async function fetch7tvGlobal() {
  try {
    const r = await fetch('https://7tv.io/v3/emote-sets/global')
    if (!r.ok) {
      console.warn(`[web/emotes] 7TV global ${r.status}`)
      return []
    }
    const j = await r.json()
    const items = j?.emotes || []
    return items.map((e) => ({
      id: e.id,
      name: e.name,
      url: `${SEVEN_TV_CDN}/${e.id}/2x`,
      animated: !!e?.data?.animated,
      source: '7tv',
    }))
  } catch (err) {
    console.warn('[web/emotes] 7TV global failed:', err.message)
    return []
  }
}

async function fetchBttvGlobal() {
  try {
    const r = await fetch('https://api.betterttv.net/3/cached/emotes/global')
    if (!r.ok) {
      console.warn(`[web/emotes] BTTV global ${r.status}`)
      return []
    }
    const items = await r.json()
    return items.map((e) => ({
      id: e.id,
      name: e.code,
      url: `${BTTV_CDN}/${e.id}/2x.${e.imageType || 'webp'}`,
      animated: !!e.animated || e.imageType === 'gif',
      source: 'bttv',
    }))
  } catch (err) {
    console.warn('[web/emotes] BTTV global failed:', err.message)
    return []
  }
}

async function fetchFfzGlobal() {
  try {
    const r = await fetch('https://api.frankerfacez.com/v1/set/global')
    if (!r.ok) {
      console.warn(`[web/emotes] FFZ global ${r.status}`)
      return []
    }
    const j = await r.json()
    const out = []
    const sets = j?.sets || {}
    for (const setKey of Object.keys(sets)) {
      const emotes = sets[setKey]?.emoticons || []
      for (const e of emotes) {
        const urls = e?.urls || {}
        const url = urls['2'] || urls['1'] || urls['4']
        if (!url) continue
        const full = url.startsWith('//') ? `https:${url}` : url
        out.push({
          id: String(e.id),
          name: e.name,
          url: full,
          animated: !!e.animated,
          source: 'ffz',
        })
      }
    }
    return out
  } catch (err) {
    console.warn('[web/emotes] FFZ global failed:', err.message)
    return []
  }
}

const __filename = fileURLToPath(import.meta.url)
const __dirname = dirname(__filename)
const OUTPUT = join(__dirname, '..', 'src', 'lib', 'stickerEmotes.generated.ts')

const start = Date.now()
const [seven, bttv, ffz] = await Promise.all([
  fetch7tvGlobal(),
  fetchBttvGlobal(),
  fetchFfzGlobal(),
])

const ms = Date.now() - start
const ts = new Date().toISOString()
const total = seven.length + bttv.length + ffz.length

const content = `// AUTO-GENERATED by scripts/fetch-emotes.mjs at ${ts}
// Do not edit by hand. Re-run \`yarn prefetch:emotes\` (or any build) to refresh.
// Total ${total} emotes (7TV ${seven.length} + BTTV ${bttv.length} + FFZ ${ffz.length}).

export interface PrefetchedEmote {
  id: string
  name: string
  url: string
  animated: boolean
  source: '7tv' | 'bttv' | 'ffz' | 'twitch' | 'kick' | 'tenor' | 'soundchain'
}

export const PREFETCHED_STICKER_EMOTES: Record<'7tv' | 'bttv' | 'ffz', PrefetchedEmote[]> = {
  '7tv': ${JSON.stringify(seven, null, 2)},
  'bttv': ${JSON.stringify(bttv, null, 2)},
  'ffz': ${JSON.stringify(ffz, null, 2)},
}
`

writeFileSync(OUTPUT, content, 'utf8')
console.log(
  `[web/emotes] Prefetched ${total} (7TV ${seven.length} + BTTV ${bttv.length} + FFZ ${ffz.length}) in ${ms}ms → src/lib/stickerEmotes.generated.ts`,
)
