import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import apolloClient from '../lib/apolloClient';
import { HomePageDocument, HomePageQuery } from '../lib/graphql';
import styles from '../styles/HomePage.module.css';
export async function getServerSideProps() {
  const {data} = await apolloClient.query<HomePageQuery>({ query: HomePageDocument });

  return {
    props: {
      books: data.books,
    },
  };
}

export interface HomePageProps {
  books: HomePageQuery['books'];
}

export default function HomePage({ books }: HomePageProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Link href="/login">
          <a className="text-2xl text-blue-500 font-semibold hover:underline">Login</a>
        </Link>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {books.map(book => (
            <div key={book.id} className={styles.card}>
              <h2>{book.title}</h2>
              <p>Created at {book.createdAt}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
