import Head from 'next/head';
import Image from 'next/image';
import apolloClient from '../lib/apolloClient';
import { HomePageDocument, HomePageQuery, PostDocument, PostQuery } from '../lib/graphql';
import styles from '../styles/HomePage.module.css';
import { YoutubeIframe } from '../components/iframes';
export async function getServerSideProps() {
  const bookObject = await apolloClient.query<HomePageQuery>({ query: HomePageDocument });
  const postObject = await apolloClient.query<PostQuery>({ query: PostDocument });

  return {
    props: {
      books: bookObject.data.books,
      posts: postObject.data.posts,
    },
  };
}

export interface HomePageProps {
  books: HomePageQuery['books'];
  posts: PostQuery['posts'];
}

export default function HomePage({ books, posts }: HomePageProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>

        <p className={styles.description}>
          Get started by editing <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          {books.map(book => (
            <div key={book.id} className={styles.card}>
              <h2>{book.title}</h2>
              <p>Created at {book.createdAt}</p>
            </div>
          ))}
        </div>
        <div className={styles.grid}>
          {posts.map(post => (
            <div key={post.id} className={styles.card}>
              <h2>{post.owner}</h2>
              <h2>{post.textContent}</h2>
              {post.videoUrl && <YoutubeIframe videoUrl={post.videoUrl} />}
              <p>Created at {post.createdAt}</p>
            </div>
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
