/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { ContractOptions } from "web3-eth-contract";
import { EventLog } from "web3-core";
import { EventEmitter } from "events";
import {
  Callback,
  PayableTransactionObject,
  NonPayableTransactionObject,
  BlockType,
  ContractEventLog,
  BaseContract,
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type AuctionCancelled = ContractEventLog<{
  nftAddress: string;
  tokenId: string;
  0: string;
  1: string;
}>;
export type AuctionCreated = ContractEventLog<{
  nftAddress: string;
  tokenId: string;
  owner: string;
  reservePrice: string;
  startTimestamp: string;
  endTimestamp: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
}>;
export type AuctionResulted = ContractEventLog<{
  oldOwner: string;
  nftAddress: string;
  tokenId: string;
  winner: string;
  winningBid: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type BidPlaced = ContractEventLog<{
  nftAddress: string;
  tokenId: string;
  bidder: string;
  bid: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type BidRefunded = ContractEventLog<{
  nftAddress: string;
  tokenId: string;
  bidder: string;
  bid: string;
  0: string;
  1: string;
  2: string;
  3: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type PauseToggled = ContractEventLog<{
  isPaused: boolean;
  0: boolean;
}>;
export type UpdateAuction = ContractEventLog<{
  nftAddress: string;
  tokenId: string;
  reservePrice: string;
  startTime: string;
  endTime: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
}>;
export type UpdateMinBidIncrement = ContractEventLog<{
  minBidIncrement: string;
  0: string;
}>;
export type UpdatePlatformFee = ContractEventLog<{
  platformFee: string;
  0: string;
}>;
export type UpdatePlatformFeeRecipient = ContractEventLog<{
  platformFeeRecipient: string;
  0: string;
}>;

export interface SoundchainAuction extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SoundchainAuction;
  clone(): SoundchainAuction;
  methods: {
    auctions(
      arg0: string,
      arg1: number | string | BN
    ): NonPayableTransactionObject<{
      owner: string;
      reservePrice: string;
      startTime: string;
      endTime: string;
      resulted: boolean;
      0: string;
      1: string;
      2: string;
      3: string;
      4: boolean;
    }>;

    cancelAuction(
      _nftAddress: string,
      _tokenId: number | string | BN
    ): NonPayableTransactionObject<void>;

    createAuction(
      _nftAddress: string,
      _tokenId: number | string | BN,
      _reservePrice: number | string | BN,
      _startTimestamp: number | string | BN,
      _endTimestamp: number | string | BN
    ): NonPayableTransactionObject<void>;

    getAuction(
      _nftAddress: string,
      _tokenId: number | string | BN
    ): NonPayableTransactionObject<{
      _owner: string;
      _reservePrice: string;
      _startTime: string;
      _endTime: string;
      _resulted: boolean;
      0: string;
      1: string;
      2: string;
      3: string;
      4: boolean;
    }>;

    getHighestBidder(
      _nftAddress: string,
      _tokenId: number | string | BN
    ): NonPayableTransactionObject<{
      _bidder: string;
      _bid: string;
      _lastBidTime: string;
      0: string;
      1: string;
      2: string;
    }>;

    highestBids(
      arg0: string,
      arg1: number | string | BN
    ): NonPayableTransactionObject<{
      bidder: string;
      bid: string;
      lastBidTime: string;
      0: string;
      1: string;
      2: string;
    }>;

    isPaused(): NonPayableTransactionObject<boolean>;

    minBidIncrement(): NonPayableTransactionObject<string>;

    owner(): NonPayableTransactionObject<string>;

    placeBid(
      _nftAddress: string,
      _tokenId: number | string | BN
    ): PayableTransactionObject<void>;

    platformFee(): NonPayableTransactionObject<string>;

    platformFeeRecipient(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    resultAuction(
      _nftAddress: string,
      _tokenId: number | string | BN
    ): NonPayableTransactionObject<void>;

    toggleIsPaused(): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    updateAuction(
      _nftAddress: string,
      _tokenId: number | string | BN,
      _reservePrice: number | string | BN,
      _startTime: number | string | BN,
      _endTime: number | string | BN
    ): NonPayableTransactionObject<void>;

    updateMinBidIncrement(
      _minBidIncrement: number | string | BN
    ): NonPayableTransactionObject<void>;

    updatePlatformFee(
      _platformFee: number | string | BN
    ): NonPayableTransactionObject<void>;

    updatePlatformFeeRecipient(
      _platformFeeRecipient: string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    AuctionCancelled(cb?: Callback<AuctionCancelled>): EventEmitter;
    AuctionCancelled(
      options?: EventOptions,
      cb?: Callback<AuctionCancelled>
    ): EventEmitter;

    AuctionCreated(cb?: Callback<AuctionCreated>): EventEmitter;
    AuctionCreated(
      options?: EventOptions,
      cb?: Callback<AuctionCreated>
    ): EventEmitter;

    AuctionResulted(cb?: Callback<AuctionResulted>): EventEmitter;
    AuctionResulted(
      options?: EventOptions,
      cb?: Callback<AuctionResulted>
    ): EventEmitter;

    BidPlaced(cb?: Callback<BidPlaced>): EventEmitter;
    BidPlaced(options?: EventOptions, cb?: Callback<BidPlaced>): EventEmitter;

    BidRefunded(cb?: Callback<BidRefunded>): EventEmitter;
    BidRefunded(
      options?: EventOptions,
      cb?: Callback<BidRefunded>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    PauseToggled(cb?: Callback<PauseToggled>): EventEmitter;
    PauseToggled(
      options?: EventOptions,
      cb?: Callback<PauseToggled>
    ): EventEmitter;

    UpdateAuction(cb?: Callback<UpdateAuction>): EventEmitter;
    UpdateAuction(
      options?: EventOptions,
      cb?: Callback<UpdateAuction>
    ): EventEmitter;

    UpdateMinBidIncrement(cb?: Callback<UpdateMinBidIncrement>): EventEmitter;
    UpdateMinBidIncrement(
      options?: EventOptions,
      cb?: Callback<UpdateMinBidIncrement>
    ): EventEmitter;

    UpdatePlatformFee(cb?: Callback<UpdatePlatformFee>): EventEmitter;
    UpdatePlatformFee(
      options?: EventOptions,
      cb?: Callback<UpdatePlatformFee>
    ): EventEmitter;

    UpdatePlatformFeeRecipient(
      cb?: Callback<UpdatePlatformFeeRecipient>
    ): EventEmitter;
    UpdatePlatformFeeRecipient(
      options?: EventOptions,
      cb?: Callback<UpdatePlatformFeeRecipient>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "AuctionCancelled", cb: Callback<AuctionCancelled>): void;
  once(
    event: "AuctionCancelled",
    options: EventOptions,
    cb: Callback<AuctionCancelled>
  ): void;

  once(event: "AuctionCreated", cb: Callback<AuctionCreated>): void;
  once(
    event: "AuctionCreated",
    options: EventOptions,
    cb: Callback<AuctionCreated>
  ): void;

  once(event: "AuctionResulted", cb: Callback<AuctionResulted>): void;
  once(
    event: "AuctionResulted",
    options: EventOptions,
    cb: Callback<AuctionResulted>
  ): void;

  once(event: "BidPlaced", cb: Callback<BidPlaced>): void;
  once(
    event: "BidPlaced",
    options: EventOptions,
    cb: Callback<BidPlaced>
  ): void;

  once(event: "BidRefunded", cb: Callback<BidRefunded>): void;
  once(
    event: "BidRefunded",
    options: EventOptions,
    cb: Callback<BidRefunded>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "PauseToggled", cb: Callback<PauseToggled>): void;
  once(
    event: "PauseToggled",
    options: EventOptions,
    cb: Callback<PauseToggled>
  ): void;

  once(event: "UpdateAuction", cb: Callback<UpdateAuction>): void;
  once(
    event: "UpdateAuction",
    options: EventOptions,
    cb: Callback<UpdateAuction>
  ): void;

  once(
    event: "UpdateMinBidIncrement",
    cb: Callback<UpdateMinBidIncrement>
  ): void;
  once(
    event: "UpdateMinBidIncrement",
    options: EventOptions,
    cb: Callback<UpdateMinBidIncrement>
  ): void;

  once(event: "UpdatePlatformFee", cb: Callback<UpdatePlatformFee>): void;
  once(
    event: "UpdatePlatformFee",
    options: EventOptions,
    cb: Callback<UpdatePlatformFee>
  ): void;

  once(
    event: "UpdatePlatformFeeRecipient",
    cb: Callback<UpdatePlatformFeeRecipient>
  ): void;
  once(
    event: "UpdatePlatformFeeRecipient",
    options: EventOptions,
    cb: Callback<UpdatePlatformFeeRecipient>
  ): void;
}
