import Button from 'components/Button';
import Link from 'components/Link';
import useMe from 'hooks/useMe';
import { setJwt } from 'lib/apollo';
import Head from 'next/head';
import Image from 'next/image';

export default function HomePage() {
  const me = useMe();

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="flex-1 flex flex-col items-center justify-center px-4">
        <h1 className="text-6xl mb-8">
          Welcome to <Link href="/">Soundchain</Link>!
        </h1>

        <div className="mb-4 text-center">
          {me ? (
            <>
              <p className="mb-4">{me.profile.displayName}</p>
              <Button type="button" onClick={() => setJwt()}>
                Sign out
              </Button>
            </>
          ) : (
            <>
              <Link buttonVariant="default" href="/login">
                Login
              </Link>
              <Link className="ml-4" buttonVariant="default" href="/register">
                Register
              </Link>
            </>
          )}
        </div>
      </main>

      <footer className="h-24 border-t border-gray-100 flex justify-center">
        <a
          className="flex items-center"
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
        </a>
      </footer>
    </div>
  );
}
