import Head from 'next/head';
import { PostBox } from '../components/PostBox';
import { PostInput } from '../components/PostInput';
import { usePostsQuery } from '../lib/graphql';

export default function PostsPage() {
  const { loading, error, data } = usePostsQuery();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="mb-14">
        <PostInput />
      </div>

      {loading && <p>Loading...</p>}
      {error && <p>{error.message}</p>}
      {data?.posts.map((post, index) => (
        <PostBox key={index} body={post.body} profileId={post.profileId} />
      ))}
    </div>
  );
}
