import Head from 'next/head';
import Image from 'next/image';
import { useState } from 'react';
import { PostBox, PostInput } from '../components/PostInput';
import { apolloClient } from '../lib/apollo';
import {
  CreatePostDocument,
  CreatePostMutation,
  CreatePostMutationVariables,
  PostDocument,
  PostQuery
} from '../lib/graphql';
import styles from '../styles/HomePage.module.css';
export async function getServerSideProps() {
  const { data } = await apolloClient.query<PostQuery>({ query: PostDocument, fetchPolicy: 'no-cache' });
  return {
    props: {
      posts: [...data.posts],
    },
  };
}

export interface PostPageProps {
  posts: PostQuery['posts'];
}

export default function PostsPage({ posts }: PostPageProps) {
  const [postList, setPosts] = useState(posts);
  const fetchNewPosts = async () => {
    const { data } = await apolloClient.query<PostQuery>({ query: PostDocument, fetchPolicy: 'no-cache' });
    setPosts(data.posts);
  };

  const onCreatePost = async (text: string) => {
    const input: CreatePostMutationVariables = { input: { body: text, author: 'placeholder-author' } };
    await apolloClient.mutate<CreatePostMutation, CreatePostMutationVariables>({
      mutation: CreatePostDocument,
      variables: input,
    });
    fetchNewPosts();
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <PostInput
          onShareClick={async text => {
            onCreatePost(text);
          }}
        />

        {postListStat.map(post => (
          <PostBox key={post.id} body={post.body} author={post.author} />
        ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
