import Head from 'next/head';
import { Post } from '../components/Post';
import { PostInput } from '../components/PostInput';
import { usePostsQuery } from '../lib/graphql';

export default function PostsPage() {
  const { loading, error, data } = usePostsQuery();

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container p-4">
        <PostInput />
        {loading && <p>Loading...</p>}
        {error && <p>{error.message}</p>}
        {data?.posts.map((post, index) => (
          <Post key={index} body={post.body} profileId={post.profileId} />
        ))}
      </div>
    </div>
  );
}
