import { GetServerSideProps } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import { apolloClient } from '../lib/apollo';
import { VerifyDocument, VerifyMutation, VerifyMutationVariables } from '../lib/graphql';
import styles from '../styles/HomePage.module.css';

export const getServerSideProps: GetServerSideProps<VerificationProps> = async context => {
  const { token } = context.query;
  let success = false;
  if (token) {
    const { data } = await apolloClient.mutate<VerifyMutation, VerifyMutationVariables>({
      mutation: VerifyDocument,
      variables: { input: { token: token as string } },
    });
    if (data) {
      success = data.verify.success;
    }
  }

  return {
    props: {
      success,
    },
  };
};

export interface VerificationProps {
  success: boolean;
}

export default function VerificationPage({ success }: VerificationProps) {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>Welcome to Soundchain!</h1>

        <p className={styles.description}>
          {success ? (
            <>
              Verification complete! You can now proceed to login.
              <br />
              <Link href="/login">
                <a>Login</a>
              </Link>
            </>
          ) : (
            <>
              Verification Failed!
              <br />
              <Link href="/">
                <a>Home</a>
              </Link>
            </>
          )}
        </p>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
