import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import apolloClient from '../../lib/apolloClient';
import * as Apollo from '@apollo/client';
import styles from '../../styles/HomePage.module.css';
import { CommentInput, CommentBox } from '../../components/inputs/postComponent';
import { Mutation, PostMutationDocument, PostQuery, PostQueryDocument } from '../../lib/postGraphql';
export async function getServerSideProps() {
  const postObject = await apolloClient.query<PostQuery>({ query: PostQueryDocument });
  const reversedPost = [...postObject.data.posts].reverse();
  return {
    props: {
      posts: reversedPost,
    },
  };
}

export interface CommentPageProps {
  posts: PostQuery['posts'];
}

export default function CommentsPage({ posts }: CommentPageProps) {
  const [postListStat, setPosts] = useState(posts);
  const [addPost] = Apollo.useMutation<Mutation>(PostMutationDocument);

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CommentInput
          onShare={async text => {
            await addPost({
              variables: {
                input: { textContent: text, owner: 'placeholder-owner' },
              },
            }).then(onfulfilled => {
              setPosts([...postListStat, onfulfilled.data?.addPost.post].reverse());
            });
          }}
        />

        <div className={styles.grid}>
          {postListStat.map(post => (
            <CommentBox
              key={post.id}
              textContent={post.textContent}
              replies={[]}
              owner={post.owner}
              videoUrl={post.videoUrl}
            />
          ))}
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
