import { useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import apolloClient from '../../lib/apolloClient';
import * as Apollo from '@apollo/client';
import styles from '../../styles/HomePage.module.css';
import { CommentInput, CommentBox } from '../../components/inputs/postComponent';
import { Mutation, PostQuery, PostDocument, CreatePostDocument } from '../../lib/graphql';
export async function getServerSideProps() {
  const postObject = await apolloClient.query<PostQuery>({ query: PostDocument });
  return {
    props: {
      posts: [...postObject.data.posts].reverse(),
    },
  };
}

export interface CommentPageProps {
  posts: PostQuery['posts'];
}

export default function CommentsPage({ posts }: CommentPageProps) {
  const [postListStat, setPosts] = useState(posts);
  const onPost = async (text: string) => {
    const input: CreatePostMutationVariables = { input: { body: text, author: 'placeholder-author' } };
    await apolloClient.mutate<CreatePostMutation, CreatePostMutationVariables>({
      mutation: CreatePostDocument,
      variables: input,
    });
    const postObject = await apolloClient.query<PostQuery>({ query: PostDocument });
    setPosts([...postObject.data.posts]);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <CommentInput
          onShare={async text => {
            await addPost({
              variables: {
                input: { body: text, author: 'placeholder-author' },
              },
            }).then(async () => {
             const postObject = await apolloClient.query<PostQuery>({ query: PostDocument });
             setPosts( [...postObject.data.posts].reverse())
            });
          }}
        />

          {postListStat.map(post => (
            <CommentBox
              key={post.id}
              body={post.body}
              author={post.author}
            />
          ))}
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
