fragment ProfileComponentFields on Profile {
  id
  displayName
  profilePicture
  coverPicture
  socialMedias {
    facebook
    instagram
    soundcloud
    twitter
    linktree
    discord
    telegram
    spotify
    bandcamp
    x
    tiktok
    onlyfans
    customLink
  }
  favoriteGenres
  musicianTypes
  bio
  followerCount
  followingCount
  tracksCount
  userHandle
  isFollowed
  isSubscriber
  unreadNotificationCount
  unreadMessageCount
  verified
  teamMember
  magicWalletAddress
  badges
  createdAt
  updatedAt
}
