/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import BN from "bn.js";
import { EventEmitter } from "events";
import { EventLog } from "web3-core";
import { ContractOptions } from "web3-eth-contract";
import {
  BaseContract, BlockType, Callback, ContractEventLog, NonPayableTransactionObject, PayableTransactionObject
} from "./types";

export interface EventOptions {
  filter?: object;
  fromBlock?: BlockType;
  topics?: string[];
}

export type ItemCanceled = ContractEventLog<{
  owner: string;
  nft: string;
  tokenId: string;
  0: string;
  1: string;
  2: string;
}>;
export type ItemListed = ContractEventLog<{
  owner: string;
  nft: string;
  tokenId: string;
  quantity: string;
  pricePerItem: string;
  OGUNPricePerItem: string;
  acceptsMATIC: boolean;
  acceptsOGUN: boolean;
  startingTime: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
  6: boolean;
  7: boolean;
  8: string;
}>;
export type ItemSold = ContractEventLog<{
  seller: string;
  buyer: string;
  nft: string;
  tokenId: string;
  quantity: string;
  pricePerItem: string;
  isPaymentOGUN: boolean;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: string;
  6: boolean;
}>;
export type ItemUpdated = ContractEventLog<{
  owner: string;
  nft: string;
  tokenId: string;
  newPrice: string;
  newOGUNPrice: string;
  acceptsMATIC: boolean;
  acceptsOGUN: boolean;
  startingTime: string;
  0: string;
  1: string;
  2: string;
  3: string;
  4: string;
  5: boolean;
  6: boolean;
  7: string;
}>;
export type OwnershipTransferred = ContractEventLog<{
  previousOwner: string;
  newOwner: string;
  0: string;
  1: string;
}>;
export type UpdatePlatformFee = ContractEventLog<{
  platformFee: string;
  0: string;
}>;
export type UpdatePlatformFeeRecipient = ContractEventLog<{
  platformFeeRecipient: string;
  0: string;
}>;

export interface SoundchainMarketplace extends BaseContract {
  constructor(
    jsonInterface: any[],
    address?: string,
    options?: ContractOptions
  ): SoundchainMarketplace;
  clone(): SoundchainMarketplace;
  methods: {
    OGUNToken(): NonPayableTransactionObject<string>;

    buyItem(
      _nftAddress: string,
      _tokenId: number | string | BN,
      _owner: string,
      _isPaymentOGUN: boolean
    ): PayableTransactionObject<void>;

    cancelListing(
      _nftAddress: string,
      _tokenId: number | string | BN
    ): NonPayableTransactionObject<void>;

    feeRecipient(): NonPayableTransactionObject<string>;

    listItem(
      _nftAddress: string,
      _tokenId: number | string | BN,
      _quantity: number | string | BN,
      _pricePerItem: number | string | BN,
      _OGUNPricePerItem: number | string | BN,
      _acceptsMATIC: boolean,
      _acceptsOGUN: boolean,
      _startingTime: number | string | BN
    ): NonPayableTransactionObject<void>;

    listings(
      arg0: string,
      arg1: number | string | BN,
      arg2: string
    ): NonPayableTransactionObject<{
      quantity: string;
      pricePerItem: string;
      OGUNPricePerItem: string;
      acceptsMATIC: boolean;
      acceptsOGUN: boolean;
      startingTime: string;
      0: string;
      1: string;
      2: string;
      3: boolean;
      4: boolean;
      5: string;
    }>;

    owner(): NonPayableTransactionObject<string>;

    platformFee(): NonPayableTransactionObject<string>;

    renounceOwnership(): NonPayableTransactionObject<void>;

    transferOwnership(newOwner: string): NonPayableTransactionObject<void>;

    updateListing(
      _nftAddress: string,
      _tokenId: number | string | BN,
      _newPrice: number | string | BN,
      _newOGUNPrice: number | string | BN,
      _acceptsMATIC: boolean,
      _acceptsOGUN: boolean,
      _startingTime: number | string | BN
    ): NonPayableTransactionObject<void>;

    updatePlatformFee(
      _platformFee: number | string | BN
    ): NonPayableTransactionObject<void>;

    updatePlatformFeeRecipient(
      _platformFeeRecipient: string
    ): NonPayableTransactionObject<void>;
  };
  events: {
    ItemCanceled(cb?: Callback<ItemCanceled>): EventEmitter;
    ItemCanceled(
      options?: EventOptions,
      cb?: Callback<ItemCanceled>
    ): EventEmitter;

    ItemListed(cb?: Callback<ItemListed>): EventEmitter;
    ItemListed(options?: EventOptions, cb?: Callback<ItemListed>): EventEmitter;

    ItemSold(cb?: Callback<ItemSold>): EventEmitter;
    ItemSold(options?: EventOptions, cb?: Callback<ItemSold>): EventEmitter;

    ItemUpdated(cb?: Callback<ItemUpdated>): EventEmitter;
    ItemUpdated(
      options?: EventOptions,
      cb?: Callback<ItemUpdated>
    ): EventEmitter;

    OwnershipTransferred(cb?: Callback<OwnershipTransferred>): EventEmitter;
    OwnershipTransferred(
      options?: EventOptions,
      cb?: Callback<OwnershipTransferred>
    ): EventEmitter;

    UpdatePlatformFee(cb?: Callback<UpdatePlatformFee>): EventEmitter;
    UpdatePlatformFee(
      options?: EventOptions,
      cb?: Callback<UpdatePlatformFee>
    ): EventEmitter;

    UpdatePlatformFeeRecipient(
      cb?: Callback<UpdatePlatformFeeRecipient>
    ): EventEmitter;
    UpdatePlatformFeeRecipient(
      options?: EventOptions,
      cb?: Callback<UpdatePlatformFeeRecipient>
    ): EventEmitter;

    allEvents(options?: EventOptions, cb?: Callback<EventLog>): EventEmitter;
  };

  once(event: "ItemCanceled", cb: Callback<ItemCanceled>): void;
  once(
    event: "ItemCanceled",
    options: EventOptions,
    cb: Callback<ItemCanceled>
  ): void;

  once(event: "ItemListed", cb: Callback<ItemListed>): void;
  once(
    event: "ItemListed",
    options: EventOptions,
    cb: Callback<ItemListed>
  ): void;

  once(event: "ItemSold", cb: Callback<ItemSold>): void;
  once(event: "ItemSold", options: EventOptions, cb: Callback<ItemSold>): void;

  once(event: "ItemUpdated", cb: Callback<ItemUpdated>): void;
  once(
    event: "ItemUpdated",
    options: EventOptions,
    cb: Callback<ItemUpdated>
  ): void;

  once(event: "OwnershipTransferred", cb: Callback<OwnershipTransferred>): void;
  once(
    event: "OwnershipTransferred",
    options: EventOptions,
    cb: Callback<OwnershipTransferred>
  ): void;

  once(event: "UpdatePlatformFee", cb: Callback<UpdatePlatformFee>): void;
  once(
    event: "UpdatePlatformFee",
    options: EventOptions,
    cb: Callback<UpdatePlatformFee>
  ): void;

  once(
    event: "UpdatePlatformFeeRecipient",
    cb: Callback<UpdatePlatformFeeRecipient>
  ): void;
  once(
    event: "UpdatePlatformFeeRecipient",
    options: EventOptions,
    cb: Callback<UpdatePlatformFeeRecipient>
  ): void;
}
